### ISSUE TITLE
Application reference code

### ISSUE THREAD

**Issue by HeyAnduin** [comp5212-AI-dots-boxes/alphazero_dots_and_boxes#1]
你好，请问我可以参考你的代码用于中国的博弈比赛吗？
Hello, may I refer to your code for the game competition in China?
Thx

**Comment by whj0401** [comment]
可以，不过请注明参考了 https://zhuanlan.zhihu.com/p/32089487
我这个也是参考了Junxiao Song的代码 https://github.com/junxiaosong/AlphaZero_Gomoku
